# Generated by Django 4.2 on 2023-05-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('trending', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
